### ISSUE TITLE
Log f64 as numbers

### ISSUE THREAD

**Issue by yanns** [LukeMathWalker/tracing-bunyan-formatter#13]
In the [`Visit` implementation for `JsonStorage`](https://github.com/LukeMathWalker/tracing-bunyan-formatter/blob/master/src/storage_layer.rs#L50), there is no implementation for f64.

It means that the default implementation is used:
```
    fn record_f64(&mut self, field: &Field, value: f64) {
        self.record_debug(field, &value)
    }
```

And f64 numbers are then logged as Strings.
I don't know if it's on purpose or not.

In our case, we prefer logging those numbers as numbers so that the log system can make sense of them.
I just had to add this code to make it work:
```
impl Visit for JsonStorage<'_> {
    fn record_f64(&mut self, field: &Field, value: f64) {
        self.values
            .insert(field.name(), serde_json::Value::from(value));
    }
```

If you think that this should be upstream, I can open a PR with that.

**Comment by LukeMathWalker** [comment]
That's indeed an oversight - a PR would be welcome!
