### ISSUE TITLE
Using `make_writer_for` instead of `make_writer`

### ISSUE THREAD

**Issue by sdether** [LukeMathWalker/tracing-bunyan-formatter#15]
I ran across a usability issue regarding capturing context when filtering above 'INFO`:

`tracing::instrument` as well as the default spans in `tracing-actix-web` are `INFO` spans, so if your filter is set at above `INFO` those spans never get recorded and their context is not included in `WARN` (for example) output. This is true even if `JsonStorageLayer` runs at `INFO` and only the formatting layer is filtered to `WARN` via  `.with_filter(EnvFilter::new("INFO")` because the `WARN` event will not see its `INFO` parent span, and hence cannot get at the context in `JsonStorageLayer`.

This is not a problem unique to `tracing-bunyan-formatter`. The same happens with `tracing_subscriber::fmt::layer()`.

The workaround is to use `MakeWriter` level filtering via `writer.with_max_level()`. However, this does not currently work with `BunyanFormattingLayer` because it relies on `make_writer_for` so that it can deactivate the write based on meta-data. I've tested out changing `BunyanFormattingLayer` to pass event/span `Metadata` to `.emit()` and calling `make_writer_for` and that seems to work, but wanted to check whether this is an acceptable modification before submitting a PR.

**Comment by mustafasegf** [comment]
Hi there, can I implement this? I really need this feature and would love to implement it

**Comment by LukeMathWalker** [comment]
I'm not 100% sure I follow the consequences of this change, but happy to have a look at the code to evaluate.
