### ISSUE TITLE
Can we have easier pretty log for development?

### ISSUE THREAD

**Issue by frederikhors** [LukeMathWalker/tracing-bunyan-formatter#17]
Hi @LukeMathWalker, I got here thanks to [your website page](https://www.lpalmieri.com/posts/2020-09-27-zero-to-production-4-are-we-observable-yet/). Very useful, much appreciated! :pray:

I would like to ask you if there is an easier way to have the logs in JSON only when required and the logs "pretty" when I am developing. Coming from Golang, this is [what `zerolog` does](https://github.com/rs/zerolog#pretty-logging) using a simple configuration (which can also be based on the value of an environment variable).

This would save us both installing your great "`bunyan`" port, and piping each time the command (`cargo watch ... | bunyan`).

**Comment by LukeMathWalker** [comment]
Hey!
You can achieve this by confusing your `tracing::Subscriber` to use different logging layers based on some kind of configuration - see https://docs.rs/tracing-subscriber/latest/tracing_subscriber/index.html for the relevant APIs.

It's not a concern of `tracing-bunyan-formatter` I'd say.

**Comment by LukeMathWalker** [comment]
I'd suggest looking at https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/index.html in particular.

**Comment by frederikhors** [comment]
As I'm not very familiar with Rust, can you please help me figure out how?

It would also be useful for other people.

I reread your post but I don't understand how I can fix it.

Please, excuse my limitation.

**Comment by LukeMathWalker** [comment]
Sure, no problem.
Here it's an example:

```rust
use tracing::{info, Subscriber};
use tracing_bunyan_formatter::{BunyanFormattingLayer, JsonStorageLayer};
use tracing_subscriber::filter::filter_fn;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::{Layer, Registry};

#[derive(PartialEq, Copy, Clone)]
enum Environment {
    Local,
    Production,
}

fn get_tracing_subscriber(env: Environment) -> impl Subscriber + Send + Sync + 'static {
    let emit_bunyan = env == Environment::Production;
    let bunyan_json_layer = JsonStorageLayer.with_filter(filter_fn(move |_| emit_bunyan));
    let bunyan_formatting_layer =
        BunyanFormattingLayer::new("tracing_demo".into(), std::io::stdout)
            .with_filter(filter_fn(move |_| emit_bunyan));

    let emit_pretty = env == Environment::Local;
    let pretty_formatting_layer =
        tracing_subscriber::fmt::layer().with_filter(filter_fn(move |_| emit_pretty));

    Registry::default()
        .with(bunyan_json_layer)
        .with(bunyan_formatting_layer)
        .with(pretty_formatting_layer)
}

fn main() {
    // Read this from an env variable or somewhere else
    let env = Environment::Local;
    let subscriber = get_tracing_subscriber(env);
    tracing::subscriber::set_global_default(subscriber).unwrap();

    info!("Orphan event without a parent span");
}
```

I have used `tracing_subscriber::fmt::layer()` as an example of "pretty" formatting, but you can replace it with any other layer you might fancy.
