### ISSUE TITLE
serde_json's arbitrary-precision feature breaks untagged enum deserialization

### ISSUE THREAD

**Issue by Michael-J-Ward** [LukeMathWalker/tracing-bunyan-formatter#3]
I recently incorporated tracing-bunyan-formatter into a project, and found it triggered a regression error in deserializing an untagged enum with `serde_json`.

`tracing-bunyan-formatter` enables the `arbitrary-precision` field on serde-json, which causes the bug, as explained here: https://github.com/serde-rs/json/issues/559

For what it's worth, I pulled down this crate and, and the same test fails with and without the feature (`parent_properties_are_propagated`).

EDIT:

Also, let me know if it's inappropriate for me to to notify you of a bug in another crate. I figured since it affects your users, you'd want to know.

**Comment by LukeMathWalker** [comment]
Interesting - thanks for raising the issue!
I am not sure there is anything we can do on our side (apart from potentially disabling the feature).

**Comment by LukeMathWalker** [comment]
I've released a new version of `tracing-bunyan-formatter` with an `arbitrary-precision` feature.
You can disable it with
```toml
tracing-bunyan-formatter = { version = "0.2", default-features = false }
```
