### ISSUE TITLE
Feature request: custom field values using valuable crate

### ISSUE THREAD

**Issue by fluffysquirrels** [LukeMathWalker/tracing-bunyan-formatter#30]
Hi! I'm currently using this crate for my JSON output but want to try adding custom structured values using tracing's unstable `valuable` feature flag ([in their docs](https://docs.rs/tracing/0.1.37/tracing/index.html#unstable-features)).

Looks like `tracing-bunyan-formatter` doesn't support that currently but it could be added fairly easily I think under a feature flag. I would probably use this crate to serialize the `Valuable` structs: <https://crates.io/crates/valuable-serde>.

What do you think?. Would you accept a PR for this?

**Comment by fluffysquirrels** [comment]
Got this working on a branch: <https://github.com/fluffysquirrels/tracing-bunyan-formatter/tree/valuable>

Still needs a bit of clean up: documentation and probably a unit test.

**Comment by LukeMathWalker** [comment]
Happy to add it behind a feature flag!

**Comment by fluffysquirrels** [comment]
Cool! I will work on a PR. Hopefully it will be ready tonight.

**Comment by fluffysquirrels** [comment]
PR is ready: #31.
