### ISSUE TITLE
Allow "elapsed_milliseconds" to work without the arbitrary-precision feature

### ISSUE THREAD

**Issue by dotdash** [LukeMathWalker/tracing-bunyan-formatter#6]
While working through zero2prod, I noticed that the log output was missing the `elapsed_milliseconds` field. This is because it now the depends on a non-default feature and the book has not (yet) been adapted to this change.

The issue here is that `as_millis()` returns a `u128`, which (somewhat?) makes sense for the `Duration` API, as it should handle a wide range of durations, but for the purposes of this crate, I'd argue that `u64` is sufficient, as that still allows for a range of  about 585M years, which seems plenty.

I'd therefore argue that truncating the `u128` value to a `u64` is reasonable and would allow the `elapsed_milliseconds` value to be added to the log entries without the need for the `arbitrary-precision` feature. Is there anything I'm missing? If not, I'm happy to make a PR.

**Comment by LukeMathWalker** [comment]
A PR would be welcome!
