### ISSUE TITLE
Configurable output of 'level' field

### ISSUE THREAD

**Issue by tumbl3w33d** [LukeMathWalker/tracing-bunyan-formatter#8]
Thank you for your awesome contributions to the tracing world in rust. Since I've entered reading your articles about tracing, I have also started using the bunyan formatter, not even knowing where it originated from. Meanwhile, I've filled this educational gap of mine, because I ran into an issue due to the log level conversion you do.

In the original bunyan repo it says

> While using log level names is preferred, the actual level values are integers internally

and nothing more about the actual motivation behind it. My app is running in a landscape with kotlin apps and I'm a little exotic with my log output there, so the question came up, whether I can avoid the log levels being integers. From what I saw, there's currently no direct way to configure this, so I wanted to ask you, what would be your suggested way of achieving this. Or would you consider it reasonable to consider this a feature request? As far as I could see, you actively convert to integers at some point and would just need to avoid this procedure.

**Comment by LukeMathWalker** [comment]
This is part of the `bunyan` spec for core fields: https://github.com/trentm/node-bunyan#core-fields
If you are not interested into the `bunyan` format specifically, you might want to check out `tracing`'s JSON formatter.
